version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: express_db
      MYSQL_USER: express_user
      MYSQL_PASSWORD: express_password
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
